# Generated by Django 4.2.11 on 2024-04-21 08:14

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BossTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ExecutorTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StatusTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название задачи')),
                ('description', models.CharField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(255, message='Длина поля не должна превышать 255 символов.')], verbose_name='Описание задачи')),
                ('priority', models.BooleanField(default=False, verbose_name='высокий приоритет')),
                ('date_start', models.DateTimeField(default=datetime.datetime.now, verbose_name='Начало выполнения поручения')),
                ('date_end', models.DateField(blank=True, null=True, validators=[django.core.validators.RegexValidator(code='invalid_date', message='Недопустимый формат. Введите дату в формате dd-mm-yyy', regex='^\\d{4}-\\d{2}-\\d{2}$')], verbose_name='Окончание выполнения поручения')),
                ('readiness_boss', models.BooleanField(default=False, verbose_name='Подтверждение выполнения начальником')),
                ('readiness_executor', models.BooleanField(default=False, verbose_name='Подтверждение выполнения исполнителем')),
            ],
        ),
    ]
