# Generated by Django 4.2.11 on 2024-04-21 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_tasktracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='id_boss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_as_boss', to=settings.AUTH_USER_MODEL, verbose_name='Имя_руководителя'),
        ),
        migrations.AddField(
            model_name='task',
            name='id_executor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_as_executor', to=settings.AUTH_USER_MODEL, verbose_name='Имя_исполнителя'),
        ),
        migrations.AddField(
            model_name='statustask',
            name='readiness_boss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_as_boss', to='main_tasktracker.task'),
        ),
        migrations.AddField(
            model_name='statustask',
            name='readiness_executor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_as_executor', to='main_tasktracker.task'),
        ),
        migrations.AddField(
            model_name='statustask',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_tasktracker.task'),
        ),
        migrations.AddField(
            model_name='executortask',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_as_executor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='executortask',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_tasktracker.task'),
        ),
        migrations.AddField(
            model_name='executortask',
            name='worker_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bosstask',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_as_boss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bosstask',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_tasktracker.task'),
        ),
        migrations.AddField(
            model_name='bosstask',
            name='worker_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
